NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('accounts.urls')), #logout, upgrade тут сидят - они нужны
    path('oauth/', include('allauth.urls'), name="account_login" ),   
]

handler404 = 'news.views.error_404'
handler403 = 'news.views.error_403'

news/urls.py
from django.urls import path
from .views import (
    AuthorList,
    PostList,
    PostDetail,
    PostCreateView,
    PostUpdateView,  # вьюхи yuryatlant
    PostDeleteView,
    PostSearch,
    NewsCategoryView,
    СategoryCreateView,
    CategoryDetailView,
    UnsubscribeCategory,
    SubscribeCategory,
    some_page)  # импортируем наше представление

app_name = "news"

urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам 
    # у нас останется пустым, позже станет ясно почему
    path('', PostList.as_view(), name="posts"),  # т.к. сам по себе это класс,
                                                 # то нам надо представить этот класс в виде view. 
                                                 # Для этого вызываем метод as_view
                                                 # добавим кэширование на детали товара. 
                                                 # Раз в 10 минут товар будет записываться 
                                                 # в кэш для экономии ресурсов
    path('posts/<int:pk>', 
         PostDetail.as_view(), 
         name="post"),  # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
    path('posts/create/', 
         PostCreateView.as_view(), 
         name='create'),  # localhost/posts/create/
    path('category/create/',
         СategoryCreateView.as_view(),
         name='create_category'),
    
    path('category/<int:pk>/',
         CategoryDetailView,
         name='category'),
    path('categories/subscribe/<int:pk>',
         SubscribeCategory,
         name='category_subscribe'),
    path('categories/unsubscribe/<int:pk>',
         UnsubscribeCategory,
         name='category_unsubscribe'),
    #path('categories/<str:cat_name>', CategoryDetailView, name='category'), 
    # здесь мы хотим имя категории, не цифру, поэтому str, после двоеточия - всё что угодно, как, что во вьюхе обзовём

    path('categories/',
         NewsCategoryView.as_view(),
         name='categories'),
    path('posts/update/<int:pk>',
         PostUpdateView.as_view(),
         name='update'),
    path('posts/delete/<int:pk>',
         PostDeleteView.as_view(),
         name='delete'),
    path('posts/search/',
         PostSearch.as_view(),
         name='search'),
    path('authors/',
         AuthorList.as_view(),
         name="authors"),
    path('some_page/<int:question_id>',
         some_page,
         name="some_page"),
]

user/urls.py
from django.urls import path
from . import views

app_name="user"

urlpatterns = [
    path('<int:pk>', views.profile, name="index"),
]

templates/includes/footer.html
<footer class="footer mt-auto py-3 ">
    <div class="container">
    <span class="long-string-for-cash-checking">
        {% load custom_filters %}
        {{ 2|pow:10019}}
    </span>
    <p><a href="http://localhost:8000/">© ООО Django обучалка-ковырялка. 2023</a>.</p>
    </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="#" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">        
        <span class="fs-4">НОВОСТИ</span>
      </a>
     {% with request.resolver_match.url_name as url_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a href="{% url 'news:search' %}" class="nav-link">
          
            <svg class="ico text-black" width="24" height="24" fill="currentColor">
              <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #search"></use>
          </svg>
          </a>
        </li>
        <li class="nav-item"><a href="{% url 'news:posts' %}" class="nav-link {% if url_name == 'posts' or  url_name == 'post' %}active{% endif %}" aria-current="page">Список Новостей</a></li>
        <li class="nav-item"><a href="{% url 'news:categories' %}" class="nav-link {% if url_name == 'categories' or  url_name == 'category' %}active{% endif %}">Категории</a></li>
        <li class="nav-item"><a href="{% url 'news:authors' %}" class="nav-link {% if url_name == 'authors' %}active{% endif %}">Авторы</a></li>
        <li class="nav-item"><a href="#" class="nav-link disabled">Критики</a></li>
        <li class="nav-item"><a href="#" class="nav-link disabled">О проекте</a></li>
        
         {% if user.is_authenticated %}
         <li class="nav-item">
            <a href="{% url 'user:index' user.id %}" class="nav-link"><span class="d-inline">Привет, {{ user.username }}</span></a>
            </li>
          {% endif %}
         {% if user.is_authenticated %}
       
              <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Выйти</a></li>
         {% else %}
            {% comment %} <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Войти</a></li> {% endcomment %}
            <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link">Войти</a></li>
          {% endif %}
       
      </ul>
      {% endwith %}
    </header>