NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('user/', include('user.urls')),
    path('accounts/', include('accounts.urls')), #logout, upgrade тут сидят - они нужны
    path('oauth/', include('allauth.urls'), name="account_login" ),   
]

handler404 = 'news.views.error_404'
handler403 = 'news.views.error_403'

accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import  MyCustomLoginView, upgrade_me, downgrade_me

urlpatterns = [
    path('login/', MyCustomLoginView.as_view, name='login'),
    path('logout/', LogoutView.as_view(template_name = './logout.html'),name='logout'),   
#     path('signup/', 
#          BaseRegisterView.as_view(template_name = 'signup.html'), # так и не поняла почему здесь можно обойтись без ./
#          name='signup'),
    path('upgrade/', upgrade_me, name = 'upgrade'),
    path('downgrade/', downgrade_me, name = 'downgrade')
]

news/urls.py
from django.urls import path
from .views import (
    AuthorList,
    PostList,
    PostDetail,
    PostCreateView,
    PostUpdateView,  # вьюхи yuryatlant
    PostDeleteView,
    PostSearch,
    NewsCategoryView,
    СategoryCreateView,
    CategoryDetailView,
    UnsubscribeCategory,
    SubscribeCategory,
    some_page)  # импортируем наше представление

app_name = "news"

urlpatterns = [
    # path — означает путь. В данном случае путь ко всем товарам 
    # у нас останется пустым, позже станет ясно почему
    path('', PostList.as_view(), name="posts"),  # т.к. сам по себе это класс,
                                                 # то нам надо представить этот класс в виде view. 
                                                 # Для этого вызываем метод as_view
                                                 # добавим кэширование на детали товара. 
                                                 # Раз в 10 минут товар будет записываться 
                                                 # в кэш для экономии ресурсов
    path('posts/<int:pk>', 
         PostDetail.as_view(), 
         name="post"),  # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
    path('posts/create/', 
         PostCreateView.as_view(), 
         name='create'),  # localhost/posts/create/
    path('category/create/',
         СategoryCreateView.as_view(),
         name='create_category'),
    
    path('category/<int:pk>/',
         CategoryDetailView,
         name='category'),
    path('categories/subscribe/<int:pk>',
         SubscribeCategory,
         name='category_subscribe'),
    path('categories/unsubscribe/<int:pk>',
         UnsubscribeCategory,
         name='category_unsubscribe'),
    #path('categories/<str:cat_name>', CategoryDetailView, name='category'), 
    # здесь мы хотим имя категории, не цифру, поэтому str, после двоеточия - всё что угодно, как, что во вьюхе обзовём

    path('categories/',
         NewsCategoryView.as_view(),
         name='categories'),
    path('posts/update/<int:pk>',
         PostUpdateView.as_view(),
         name='update'),
    path('posts/delete/<int:pk>',
         PostDeleteView.as_view(),
         name='delete'),
    path('posts/search/',
         PostSearch.as_view(),
         name='search'),
    path('authors/',
         AuthorList.as_view(),
         name="authors"),
    path('some_page/<int:question_id>',
         some_page,
         name="some_page"),
]

news/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post, Category, Author

choices = Category.objects.all().values_list('name','name')

class PostForm(ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    # title = forms.CharField(
    #     label = 'Заголовок поста',
    #     widget = forms.TextInput(attrs={
    #         'placeholder': 'Здесь вводим заголовок...', 
    #         'class':'form-control',
    #         'id': 'adding-item-title'
    #     })
    # )

    # text = forms.CharField(
    #     label = 'Текст поста',
    #     widget = forms.Textarea(attrs={
    #         'placeholder': 'Здесь вводим текст поста...', 
    #         'class':'form-control',
    #         'rows': 3,
    #         'id': 'adding-item-text'
    #     })
    # )

    # author = forms.ModelChoiceField(
    #     label = 'Выбираем автора',
    #     queryset = Author.objects.all(),
    #     widget=forms.Select(attrs={
    #         'class': 'form-select', 
    #         'id': 'adding-item-author'
    #     })
    # )

    # category = forms.ModelMultipleChoiceField(
    #     label = 'Выбираем категорию',
    #     # queryset = Category.objects.all(),
    #     choices = choices,
    #     widget=forms.CheckboxSelectMultiple(attrs={
             
    #         'id': 'adding-item-category'
    #     })
    # )

    # postType = forms.ChoiceField(
    #     label = 'Выбираем тип поста',
    #     widget = forms.Select(attrs={
    #         'class': 'form-select', 
    #         'id': 'adding-item-type'
    #     }), 
    #     choices=Post.TYPE
    # )

    class Meta:
        model = Post
        fields = ['title', 'text', 'author','category', 'postType']
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'text': forms.Textarea(attrs={'class':'form-control'}),
            'author': forms.Select(attrs={'class':'form-select'}),
            'category': forms.CheckboxSelectMultiple(choices=choices),
            'postType': forms.Select(choices=Post.TYPE, attrs={'class':'form-select'}),
        }
       
        labels = {
            'title' : 'Заголовок поста',
            'text' : 'Текст поста',
            'author': 'Выбираем автора',
            'category': 'Выбираем категорию',
            'postType': 'Выбираем тип'
        }

news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from datetime import timedelta
from django.utils import timezone

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import *
from .forms import PostForm
from .filters import PostFilter
from django.conf import settings
import logging

logger = logging.getLogger("django")

DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL

class AuthorList(ListView):
    model = Author
    template_name = 'news/authors.html'
    context_object_name = 'authors'
    queryset = Author.objects.order_by('name')

class PostList(ListView):
    model = Post  
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 5 # поставим постраничный вывод в n- элементов

    logger.error('-----Logging works!---------')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["dbError"] = Post.objects.get(pk=1435)
        context['time_now'] = datetime.utcnow() # добавим переменную текущей даты time_now
        context['is_author'] = self.request.user.groups.filter(name = 'authors').exists()
        # context['all_posts'] =  Post.objects.order_by('-dateCreation')
        return context

from django.core.cache import cache # импортируем наш кэш      
# создаём представление, в котором будут детали конкретного отдельного товара
class PostDetail(DetailView):
    model = Post 
    template_name = 'news/post.html'
    context_object_name = 'post'

    
    def get_object(self, *args, **kwargs): # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'post-{self.kwargs["pk"]}', None) # кэш очень похож на словарь, и метод get действует также. Он забирает значение по ключу, если его нет, то забирает None.
 
        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset) 
            cache.set(f'post-{self.kwargs["pk"]}', obj)
        
        return obj

# class based  views  выполняют за нас значительную часть задач
# function based views можно использовать также - не забывать
# Каждый раз, когда мы создаем какую-то страницу в джанге, это трехэтапный процесс - создание url, создание вью, создание темплейта
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from datetime import datetime
from django.utils import timezone
from django.utils.timezone import timedelta

class PostCreateView(UserPassesTestMixin,LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post')
    template_name = 'news/post_create.html'
    form_class = PostForm
    success_url = '/'
    login_url = settings.LOGIN_URL

    def test_func(self):
        yesterday = datetime.now() - timedelta(days=1)
        author = Author.objects.get(name_id=self.request.user.id)
        post_per_day = Post.objects.filter(author=author, dateCreation__gt=yesterday).count()
        if post_per_day > 2:
            logger.error(f"У нас потенциальный спaмер новостей: {author}")
            raise PermissionDenied("Вы уже достаточно наваяли сегодня, отдохните. Допускается постить до 3 штук в день")
        else:
            return redirect('/')
       
    def handle_no_permission(self):        
        # add custom message
        messages.error(self.request, 'Чтобы создать статью, вам нужно войти в качестве автора')
        return redirect(self.request.get_full_path(),self.get_login_url())


class NewsCategoryView(ListView):
    model = Category
    template_name = 'news/categories.html'
    context_object_name = 'categories'
    queryset = Category.objects.all()

# functional view
# def CategoryDetailView(request, pk): # легче дернуть реквест юрл чем в дженериках
#     # нам не нужна модель категорий, всё что нужно от категории - мы получили в cats урла, т.е. только её имя
#     category_posts = Post.objects.filter(category = pk) # в скобках - обращение к полю модели category (models.py - на момент написания кода - 51 строка)
   
#     category = Category.objects.get(id=pk)
#     subscribers = category.subscribers.all()
#     return render(request,'category.html', {'pk': pk, 'category' : category, 'category_posts' : category_posts, 'subscribers': subscribers}) # реквест, шаблон, словарь контекста


#from django.http import JsonResponse
@login_required
def UnsubscribeCategory(request, pk): 
    user = request.user
    category = Category.objects.get(pk=pk)

    category.subscribers.remove(request.user.id)
    result = 'Unsubscribed'
    return redirect(request.META.get('HTTP_REFERER'))
    # return JsonResponse(result, safe= False)

@login_required
def SubscribeCategory(request, pk): 
    user = request.user
    category = Category.objects.get(pk=pk)

    if not category.subscribers.filter(id=user.id).exists():
        category.subscribers.add(user)
        email = user.email
        html = render_to_string(
            'mailing/subscibed_to_cat_notification.html', 
            {
                'category': category,
                'user': user,
            },
        )
        
        msg = EmailMultiAlternatives(
            subject=f'Подтверждение подписи на категорию - {category.name}',
            body='',
            from_email= DEFAULT_FROM_EMAIL,
            to=[email,], # это то же, что и recipients_list - передаем коллекцию
        )
        
        msg.attach_alternative(html, 'text/html')
        try:
            msg.send() # отсылаем  
        except Exception as e:
            print(e)
        redirect(request.META.get('HTTP_REFERER'))
        # TODO: реализовать страницу пользователя
        # return redirect('')
    return redirect(request.META.get('HTTP_REFERER'))
    #return JsonResponse(result, safe= False)

def CategoryDetailView(request, pk):
   category = Category.objects.get(pk=pk)
   is_subscribed = True if len(category.subscribers.filter(id=request.user.id)) else False

   return render(request,'news/category.html', 
                 {'category': category,  
                  'is_subscribed' : is_subscribed, #,
                #   'subscribers': category.subscribers.all()
                  'subscribers': category.subscribers.all()
                  }) 

class СategoryCreateView(CreateView):
    model = Category
    template_name = 'news/category_create.html'
    fields = '__all__'
    # form_class = PostForm
    success_url = '/'

# проверка на то, что удаляет её создатель или админ, а не какой либо другой автор 
class PostDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post')
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = '/'
    login_url = settings.LOGIN_URL
    redirect_field_name = 'redirect_to'
    
    def handle_no_permission(self):        
        # add custom message
        messages.error(self.request, 'Чтобы удалить статью, вам нужно войти в качестве автора')
        return redirect(self.get_login_url())


# проверка на то, что редактирует её создатель или админ, а не какой либо другой автор 
# дженерик для редактирования объекта
class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post')    
    template_name = 'news/post_create.html'
    form_class = PostForm
    success_url = '/'
    login_url = settings.LOGIN_URL

    # метод get_object мы используем вместо queryset, чтобы получить информацию об объекте который мы собираемся редактировать
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)       
        context['isUpdateView'] = True        
        return context
    
    def handle_no_permission(self):        
        # add custom message
        messages.error(self.request, 'Чтобы редактировать статью, вам нужно войти в качестве автора')
        return redirect(self.get_login_url())

# log = logging.getLogger(__name__)

class PostSearch(ListView):
    model = Post  
    template_name = 'news/posts_search.html'
    context_object_name = 'posts'
    queryset = Post.objects.order_by('-dateCreation')      
    
    def get_context_data(self, **kwargs): # забираем отфильтрованные объекты переопределяя метод get_context_data у наследуемого класса (привет, полиморфизм, мы скучали!!!)
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset()) # вписываем наш фильтр в контекст
        return context

from django.views.decorators.cache import cache_page # импортируем декоратор для кэширования отдельного представления
from django.http import HttpResponse
@cache_page(60 * 15) # в аргументы к декоратору передаём количество секунд, которые хотим, чтобы страница держалась в кэше. Внимание! Пока страница находится в кэше, изменения, происходящие на ней, учитываться не будут!
def some_page(request, question_id):
    return HttpResponse("Вопрос под номером %s." % question_id)

def error_404(request, exception):
       return render(request, 'errors/404.html', { 'exception': 'Ошибочка...'})# {'exception': exception})

def error_403(request, exception):
        return render(request, 'errors/403.html', {'exception': exception})

templates/news/authors.html
{% extends 'defaultLayout.html' %} 
{% load static %}

{% load custom_filters %}

{% block title %}
    Авторы
{% endblock title %}

{% block abracadabra %}

{% if authors %}
     {% for author in authors %}
        <p>{{ author.name }}</p>
     {% endfor %}
{% else %}
    <h2 class="pb-2 border-bottom">Авторов пока нет</h2> 
    <p>Станьте первым автором!</p>
    <p>
        <a href="{% url 'news:upgrade' %}" class="btn btn-dark">
            <svg class="ico text-white" width="24" height="24" fill="currentColor">
                <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #journal-arrow-up"></use>
            </svg>Стать автором
        </a>    
    </p>          
{% endif %}
         
          
{% endblock abracadabra %}

templates/news/categories.html
{% extends 'defaultLayout.html' %} 
{% load static %}

{% load custom_filters %}

{% block title %}
    Категории
{% endblock title %}

{% block abracadabra %}
    <div class="btn-toolbar justify-content-between border-bottom pb-2 mb-5">
        <h1 class="post-title">Категории</h1>
        <a href="{% url 'news:create_category' %}" class="btn btn-success d-flex align-items-center">
            <svg class="ico text-white" width="24" height="24" fill="currentColor">
                <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #plus-lg"></use>
            </svg>Добавить категорию</a>                 
    </div>

    <div class="card-deck mb-3 text-center">
        {% for category in categories %}
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h5 class="card-title">{{ category.name }}</h5>
                    <p class="card-text text-muted">Всего постов: {{ category.post_set.all.count }}</p>
                    <a href = "{% url 'news:category' category.id %}" class="btn btn-primary stretched-link">Ознакомиться</a>
                </div>
                </div>
        {% endfor%}
    </div>

     

{% endblock abracadabra %} 
{% comment %} {% block abracadabra %} 

{% if sub %}
<div>
    <em>
        Подписаться на категорию 
        <strong> {{category}} ? </strong>
    </em>
    <button>
        <a href = "{% url 'subscribe' category.id %}" > Подписаться!</a> 
    </button>
</div>
{% else %}
<div>
    <em>
        Отписаться от категории 
        <strong> {{category}} ? </strong>
    </em>
    <button>
        {% comment %} <a href = "{% url 'unsubscribe' pk=category.id %}" > Отписаться!</a> 
    </button>
</div>
{% endif %}


{% endblock abracadabra %} {% endcomment %}

templates/news/category.html
{% extends 'defaultLayout.html' %} 
 
{% block title %}
    {{ category.name }}
{% endblock title %}
 
{% block abracadabra %}  
   <h1>
    {{ category.name }} <small class="font-italic text-muted"> Подписчиков {{ subscribers.count }} </small>
   </h1>
   {% if is_subscribed %}
        <div>
            <em>
                Отписаться от категории
                <strong> {{ category.name }} ? </strong>
            </em>
                <a href = "{% url 'news:category_unsubscribe' category.id %}" class="btn btn-outline-primary" > Отписаться!</a>
                {% comment %} <a href = "{% url 'category_unsubscribe' category.name %}" > Отписаться!</a> {% endcomment %}
        </div>
        {% else %}        
        <div>
            <em>
                Подписаться на категорию
                <strong> {{ category.name }} ? </strong>
            </em>
                <a href = "{% url 'news:category_subscribe' category.id %}" class="btn btn-primary" > Подписаться !</a>
                {% comment %} <a href = "{% url 'category_subscribe' category.name %}" > Подписаться !</a> {% endcomment %}
        </div>
    {% endif %}
    {% load custom_filters %}
    {%  for post in category.post_set.all|sort_by:'-dateCreation' %}
       <div class="row g-4 py-5 row-cols-1">
                <div class="col d-flex align-items-start">           
                    <div>
                        <h3 class="fs-2">{{ post.title }}</h3>
                        <p>{{ post.dateCreation | date:'d.m.y' }} by {{ post.author }}</p>
                        <p>{{ post.text|slice:"100"|safe }}</p>
                        <a href="{% url 'news:post' post.id %}" class="btn btn-primary btn-sm"> 
                            Читать
                        </a>
                    </div>
                </div>  
            </div>

    {% endfor %}

{% endblock abracadabra %}

templates/news/category_create.html
{% extends 'defaultLayout.html' %} 

{% block title %}
Создаем категорию
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, айди которого было передано в адрес -->
{% block abracadabra %}
{% if  user.is_authenticated %}
    <h1>Добавить категорию</h1>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value ="Добавить" class="btn btn-primary">
    
    </form>
{% else %}
Нет доступа
{% endif %}

{% endblock abracadabra %}

templates/news/post.html
{% extends 'defaultLayout.html' %} 
 
{% block title %}
{{ post.title}}
{% endblock title %}
 
{% block abracadabra %}
<h1>{{ post.title }}</h1>
<p>{{ post.text }}</p>
<p>Опубликовано {{ post.dateCreation | date:'d.m.y в h:i' }}</p>
<p> {{ post.author }}</p>

#TODO: КНОПКИ LIKE|DISLIKE

{% endblock abracadabra %}

templates/news/post_create.html
{% extends 'defaultLayout.html' %} 

{% block title %}
Создаем пост
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, айди которого было передано в адрес -->
{% block abracadabra %}


{% if isUpdateView  %}
        <h1>Редактировать пост</h1>
    {% else %}
        <h1>Добавить пост</h1>
{% endif %}


<form method="POST">
    {% csrf_token %}
    <div class="col-6 mb-3">
        {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    </div>
    {% if isUpdateView  %}
        <input type="submit" value="Сохранить изменения" class="btn btn-primary">
        {% else %}
        <input type="submit" value="Добавляем" class="btn btn-primary">
    {% endif %}
</form>



{% endblock abracadabra %}

templates/news/post_delete.html
{% extends 'defaultLayout.html' %} 
{% load static %}

{% block title %}
Удаление поста
{% endblock title %}


{% block page_styles %}
<!-- <link rel="stylesheet" href="{% static 'general.css' %}"> -->
{% endblock page_styles %}

{% block abracadabra %}
<h2>Вы действительно хотите удалить выбранный пост?</h2>
<p>  {{ post.title }}</p>
<p>  {{ post.text }}</p>

<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-outline-danger" value="подтвердить">
</form>

{% endblock abracadabra %}

templates/news/posts.html
{% extends 'defaultLayout.html' %} 
{% load static %}

{% load custom_filters %}

{% block title %}
    Статьи
{% endblock title %}

{% block abracadabra %}


            <p>Проверка фильтра цензурирования обсценной лексики:
                {% with string='ты ж бля' %}
                    {{ string|censor }}
                {% endwith %}
            </p>                          
            <p>
                 {% if user.is_authenticated %}
                    залогинен
                    {% else %}
                    не залогинен
                {% endif %}
            </p>
            <p>
                {% if is_author %}
                   Автор
                {% else %}
                    Не автор
                {% endif %}
            </p>
        {% if posts %}
        <div class="btn-toolbar justify-content-between border-bottom pb-2 mb-5">
           <h2 class="post-title">Всего статей <span>{{ paginator.count }} штук(и)</span> </h2>
            {% if is_author %}
                <div>
                    <a href="{% url 'news:create' %}" class="btn btn-success">
                    <svg class="ico text-white" width="24" height="24" fill="currentColor">
                        <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #journal-medical"></use>
                    </svg>Добавить статью
                </a>  
                <a href="{% url 'downgrade' %}" class="btn btn-outline-dark"> 
                    <svg class="ico text-dark" width="24" height="24" fill="currentColor">
                        <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #journal-minus"></use>
                    </svg>уволиться из  авторов
                    </a>
                </div>
            {% else %} 
                <a href="{% url 'upgrade' %}" class="btn btn-dark">
                    <svg class="ico text-white" width="24" height="24" fill="currentColor">
                        <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #journal-arrow-up"></use>
                    </svg>Стать автором
                </a>    
            {% endif%}        
        </div>
        
        {% if paginator.count > 5 %}            
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">Первая страница</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                            <a class="page-link">{{ num }}</a>
                        </li>
                       
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li> 
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
                    </li>                   
                   
              {% endif %}
              
            </ul>
          </nav>            
        {% endif%} 
            <h3>Сегодня:  {{ time_now|date:'M d Y' }}</h3>
            {% comment %} <h2>Raise dbError: {{ dbError }}</h2> {% endcomment %}
            <!-- <h3> За дату: {{ time_now|date:'M d Y' }}</h3> -->
            {% comment %} {% for post in all_posts %} {% endcomment %}
             {% for post in posts %}
            <div class="row g-4 py-5 row-cols-1">
                <div class="col d-flex align-items-start">           
                    <div>
                        <h3 class="fs-2">{{ post.title }}</h3>
                        <p>
                            {% for category in post.category.all %}                            
                                <span class="badge text-bg-secondary">{{ category.name }}</span>
                            {% endfor%}
                        </p>
                        <p>{{ post.get_category_type}} от {{ post.dateCreation | date:'d.m.y' }} от {{ post.author }}</p>
                        <p>{{ post.preview | truncatechars:50 }}</p>
                        {% if is_author %}
                            <a href="{% url 'news:update' post.id %}" class="btn btn-outline-primary btn-sm">
                             <svg class="ico" width="16" height="16" fill="currentColor">
                                <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #journal-text"></use>
                            </svg>
                            Редактировать</a>
                            <a href="{% url 'news:delete' post.id %}" class="btn btn-outline-danger btn-sm">
                                 <svg class="ico" width="16" height="16" fill="currentColor">
                                    <use xlink:href="{% static 'img/bootstrap-icons.svg' %} #journal-x"></use>
                                </svg>
                            Удалить</a>
                        {% endif%}     
                        <a href="{% url 'news:post' post.id %}" class="btn btn-primary btn-sm">
                            Читать
                        </a>
                    </div>
                </div>  
            </div>
            {% endfor %}
        {% else %}
            <h2 class="pb-2 border-bottom">Статей пока нет</h2>           
         {% endif %}
         
          
{% endblock abracadabra %}

templates/news/posts_search.html
{% extends 'defaultLayout.html' %} 

{% load widget_tweaks %}

{% load custom_filters %}

{% block title %}
    Поиск по статьям
{% endblock title %}

{% block abracadabra %}                                    


    <form method="GET">
        <div class="row  align-items-end">
            <div class="col">
                {{ filter.form.title.label_tag }}            
                {% render_field filter.form.title class="form-control" placeholder="Заголовок статьи"%}
               
            </div>
            <div class="col">
                {{ filter.form.dateCreation.label_tag }}            
                {% render_field filter.form.dateCreation class="form-control" %}
               
            </div>
            <div class="col">
                {{ filter.form.author }}            
                {% render_field filter.form.author class="form-select" %}
               
            </div>
            
            <div class="col-auto">
                <button type="submit" class="btn btn-primary">Найти</button>
              </div>
        </div>
    </form>
    <!-- {{ filter.form }}  -->
    <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самому -->
   


{% for post in filter.qs %}
<div class="row g-4 py-5 row-cols-1">
    <div class="col d-flex align-items-start">           
        <div>
            <h3 class="fs-2">{{ post.title }}</h3>
            <p>{{ post.dateCreation | date:'d.m.y' }} by {{ post.author }}</p>
            <p>{{ post.preview | truncatechars:50 }}</p>
            <p>
                {% for category in post.category.all %}                
                 <span class="badge text-bg-secondary">{{ category.name }}</span>
                {% endfor%}
            </p>
            <a href="{% url 'news:update' post.id %}" class="btn btn-outline-primary btn-sm">Редактировать</a>
            <a href="{% url 'news:delete' post.id %}" class="btn btn-outline-danger btn-sm">Удалить</a>
            <a href="{% url 'news:post' post.id %}" class="btn btn-primary btn-sm">
                Читать
            </a>
        </div>
    </div>  
</div>
{% endfor %}

{% endblock abracadabra %}